// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkP3gypmQHs_CrrBgiy7IXMDz_VVJDGvw',
    appId: '1:936868961990:web:022a545478ec5b5fa501c7',
    messagingSenderId: '936868961990',
    projectId: 'mangrov-cf6e2',
    authDomain: 'mangrov-cf6e2.firebaseapp.com',
    storageBucket: 'mangrov-cf6e2.firebasestorage.app',
    measurementId: 'G-PC68SEG8KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFSNVuaG2FqFQZPig_sM1qT6JOa51_JEY',
    appId: '1:936868961990:android:aecb96117437bce9a501c7',
    messagingSenderId: '936868961990',
    projectId: 'mangrov-cf6e2',
    storageBucket: 'mangrov-cf6e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAquFAk-KhcEX3pVMo9jGI0aDK6c0fUhgw',
    appId: '1:936868961990:ios:afbf3d8141eb0952a501c7',
    messagingSenderId: '936868961990',
    projectId: 'mangrov-cf6e2',
    storageBucket: 'mangrov-cf6e2.firebasestorage.app',
    iosBundleId: 'com.example.mangrov',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAquFAk-KhcEX3pVMo9jGI0aDK6c0fUhgw',
    appId: '1:936868961990:ios:afbf3d8141eb0952a501c7',
    messagingSenderId: '936868961990',
    projectId: 'mangrov-cf6e2',
    storageBucket: 'mangrov-cf6e2.firebasestorage.app',
    iosBundleId: 'com.example.mangrov',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkP3gypmQHs_CrrBgiy7IXMDz_VVJDGvw',
    appId: '1:936868961990:web:90f6ce526a6f492ba501c7',
    messagingSenderId: '936868961990',
    projectId: 'mangrov-cf6e2',
    authDomain: 'mangrov-cf6e2.firebaseapp.com',
    storageBucket: 'mangrov-cf6e2.firebasestorage.app',
    measurementId: 'G-WENE6QYKT6',
  );

}